### ISSUE TITLE
Amazing 

### ISSUE THREAD

**Issue by lvxingtu** [palexdev/VirtualizedFX#1]
From reddit, I try to do it. 
Can you provide some learn material for virtual flow?

**Comment by palexdev** [comment]
> From reddit, I try to do it.
> Can you provide some learn material for virtual flow?

Yeah, sorry for that, I definitely have to add a README, but currently I'm focused 100% on [MaterialFX](https://github.com/palexdev/MaterialFX) which is going to receive a huge update soon, so, you'll have to wait a little or... you could see MFXListView and MFXListViewSkin from MaterialFX since they use VirtualizedFX

**Comment by lvxingtu** [comment]
I mean I want to learn how to implement this and join this project.
