### ISSUE TITLE
Question about VirtualGrid

### ISSUE THREAD

**Issue by ouaibsky** [palexdev/VirtualizedFX#10]
Hi

I's more q question to help to understand if VirtualizedFlow could be a replacement for my usage of GridView (ControlFx).

I browsed a little bit the code and can you confirm:
* There is no selection model in place ?
* Is it possible to scroll programmatically to one item, like we can do with ListView and MultipleSelectionModel:
```java
                MultipleSelectionModel<...> selectionModel = listView.getSelectionModel();
                selectionModel.select(T);
                listView.scrollTo(T);
```   

Thx in advance
Chris.

**Comment by palexdev** [comment]
Hello @ouaibsky,
You are correct VirtualizedFX offers the building blocks for List, Grid and Table views.
So, there are no selection models.

There are several, methods that allow you to scroll programmatically, but there's no `scrollTo(T)`
I didn't think about it because it could be quite heavy on performance for huge lists since you'd have to first get the index of the item through `indexOf(T)`
The behavior can be easily achieved though since there's a similar method `scrollTo(index)`

Edit: I just realized that you asked about VirtualGrid. There are similar methods to the ones described above for the grid too.
However, my implementation is completely different from others who still use a VirtualFlow as "backend". My grid is a **real** grid. Even the used data structure is not a List but an observable and dynamic matrix

Please make sure to read both the README and javadocs, everything is well described and documented.
I just want to remember that this section is for _issues_ not questions

**Comment by ouaibsky** [comment]
Understood, thx for your answer.
